// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch_UI

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TimeContainer = NULL;
lv_obj_t * ui_Hour = NULL;
lv_obj_t * ui_Minutes = NULL;
lv_obj_t * ui_Seconds = NULL;
lv_obj_t * ui_ColonMin = NULL;
lv_obj_t * ui_Day = NULL;
lv_obj_t * ui_Date = NULL;
lv_obj_t * ui_BatteryContainer = NULL;
lv_obj_t * ui_BatteryLabel = NULL;
lv_obj_t * ui_BatteryBar = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x140644), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_TimeContainer);
    lv_obj_set_width(ui_TimeContainer, 221);
    lv_obj_set_height(ui_TimeContainer, 151);
    lv_obj_set_x(ui_TimeContainer, 0);
    lv_obj_set_y(ui_TimeContainer, -16);
    lv_obj_set_align(ui_TimeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeContainer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeContainer, lv_color_hex(0x1A0554), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour, -59);
    lv_obj_set_y(ui_Hour, -10);
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "00");
    lv_obj_set_style_text_color(ui_Hour, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minutes = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_Minutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minutes, 22);
    lv_obj_set_y(ui_Minutes, -10);
    lv_obj_set_align(ui_Minutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minutes, "00");
    lv_obj_set_style_text_color(ui_Minutes, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minutes, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Seconds = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_Seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Seconds, 81);
    lv_obj_set_y(ui_Seconds, 5);
    lv_obj_set_align(ui_Seconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Seconds, "00");
    lv_obj_set_style_text_color(ui_Seconds, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Seconds, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColonMin = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_ColonMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ColonMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ColonMin, -19);
    lv_obj_set_y(ui_ColonMin, -10);
    lv_obj_set_align(ui_ColonMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ColonMin, ":");
    lv_obj_set_style_text_color(ui_ColonMin, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ColonMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ColonMin, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Day = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_Day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Day, -45);
    lv_obj_set_y(ui_Day, 36);
    lv_obj_set_align(ui_Day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Day, "Thursday");
    lv_obj_set_style_text_color(ui_Day, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Day, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 49);
    lv_obj_set_y(ui_Date, 46);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "30/12");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryContainer, 81);
    lv_obj_set_height(ui_BatteryContainer, 50);
    lv_obj_set_x(ui_BatteryContainer, 71);
    lv_obj_set_y(ui_BatteryContainer, 109);
    lv_obj_set_align(ui_BatteryContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BatteryContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryContainer, lv_color_hex(0x2B0E48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryLabel = lv_label_create(ui_BatteryContainer);
    lv_obj_set_width(ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabel, 2);
    lv_obj_set_y(ui_BatteryLabel, -13);
    lv_obj_set_align(ui_BatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryLabel, "100%");
    lv_obj_set_style_text_color(ui_BatteryLabel, lv_color_hex(0x00F943), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBar = lv_bar_create(ui_BatteryContainer);
    lv_bar_set_value(ui_BatteryBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 65);
    lv_obj_set_height(ui_BatteryBar, 21);
    lv_obj_set_x(ui_BatteryBar, 2);
    lv_obj_set_y(ui_BatteryBar, 7);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TimeContainer = NULL;
    ui_Hour = NULL;
    ui_Minutes = NULL;
    ui_Seconds = NULL;
    ui_ColonMin = NULL;
    ui_Day = NULL;
    ui_Date = NULL;
    ui_BatteryContainer = NULL;
    ui_BatteryLabel = NULL;
    ui_BatteryBar = NULL;

}
