// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Smartwatch_UI

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TimeContainer;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Minutes;
extern lv_obj_t * ui_Seconds;
extern lv_obj_t * ui_ColonMin;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_BatteryContainer;
extern lv_obj_t * ui_BatteryLabel;
extern lv_obj_t * ui_BatteryBar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

